[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ratekeep"
version = "0.1.0"
description = "Adaptive Rate Limiting SDK"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "redis>=4.0.0"
]

[project.optional-dependencies]
fastapi = ["fastapi", "starlette"]
flask = ["flask"]

[tool.setuptools.packages.find]
include = ["ratekeep*"]